// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmshbggGkQCd3u1NNcABq66nOj5fO8_oA',
    appId: '1:596392961975:web:fd686906f1417e78e8aa32',
    messagingSenderId: '596392961975',
    projectId: 'ggsignin-d8fc2',
    authDomain: 'ggsignin-d8fc2.firebaseapp.com',
    storageBucket: 'ggsignin-d8fc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe2d-1ytrKs0WAFxtOS-kaGaDUqkUOqzE',
    appId: '1:596392961975:android:a1e5a69680d2a92ce8aa32',
    messagingSenderId: '596392961975',
    projectId: 'ggsignin-d8fc2',
    storageBucket: 'ggsignin-d8fc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZiKDgHDe3JVwdnrwQwYqYfmpcSY_TODI',
    appId: '1:596392961975:ios:319f06d7fe02ab59e8aa32',
    messagingSenderId: '596392961975',
    projectId: 'ggsignin-d8fc2',
    storageBucket: 'ggsignin-d8fc2.firebasestorage.app',
    iosClientId: '596392961975-r33b4qq8rc3ro0lbpg1qphavsnto4un8.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonShopOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZiKDgHDe3JVwdnrwQwYqYfmpcSY_TODI',
    appId: '1:596392961975:ios:319f06d7fe02ab59e8aa32',
    messagingSenderId: '596392961975',
    projectId: 'ggsignin-d8fc2',
    storageBucket: 'ggsignin-d8fc2.firebasestorage.app',
    iosClientId: '596392961975-r33b4qq8rc3ro0lbpg1qphavsnto4un8.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonShopOn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmshbggGkQCd3u1NNcABq66nOj5fO8_oA',
    appId: '1:596392961975:web:e39b728fca389d84e8aa32',
    messagingSenderId: '596392961975',
    projectId: 'ggsignin-d8fc2',
    authDomain: 'ggsignin-d8fc2.firebaseapp.com',
    storageBucket: 'ggsignin-d8fc2.firebasestorage.app',
  );

}